### ISSUE TITLE
need to install .net

### ISSUE THREAD

**Issue by frlp542** [michiproep/ScreenshareHelper#3]
application is always requesting to install .net even when the latest version is installed (5.0.7)

Greetings

Filip

**Comment by michiproep** [comment]
Hi @frlp542 , I'll need check what's going wrong here. I'll keep you updated.
Can you share your runtimes list since I'm not able to reproduce this for now?
`dotnet --list-runtimes`

Mine is looking like this.
Microsoft.AspNetCore.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by frlp542** [comment]
This is my output

Microsoft.NETCore.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Greetings

**Comment by frlp542** [comment]
ok, found something ...
Description: A .NET application failed.
Application: ScreenshareHelper.exe
Path: C:\Program Files\dotnet\ScreenshareHelper.exe
Message: A fatal error occurred. The required library hostfxr.dll could not be found.
If this is a self-contained application, that library should exist in [C:\Program Files\dotnet\].
If this is a framework-dependent application, install the runtime in the global location [C:\Program Files (x86)\dotnet] or use the DOTNET_ROOT(x86) environment variable to specify the runtime location or register the runtime location in [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation].

The .NET runtime can be found at:
  - https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=x86&rid=win10-x86&apphost_version=5.0.5

a path issue could be the reason, I'll check it out

**Comment by ImaBadCoder** [comment]
I am getting the same error. Would love to use this tool as it seems to solve my issue for sharing out a specific fancyzone window. Let me know if you need any troubleshooting info from my computer.

**Comment by ImaBadCoder** [comment]
So, installing the desktop x86 version fixed the issue. I am able to start the application now.

https://dotnet.microsoft.com/download/dotnet/thank-you/runtime-desktop-5.0.7-windows-x86-installer

Thanks so much.

**Comment by michiproep** [comment]
You are right. I published with target runtime x86. I will add both, x86 and x64
