### ISSUE TITLE
Teams recording just shows black window

### ISSUE THREAD

**Issue by RicardoNiepel** [michiproep/ScreenshareHelper#6]
Thus it seems the painting is not suuccesful.

Any known issues with Window 10 21H1?

**Comment by michiproep** [comment]
Hi @RicardoNiepel,
currently I run 
![grafik](https://user-images.githubusercontent.com/12296115/132451559-4568fec2-9f8a-45ba-910c-0370161619c9.png)
This is due to restrictions of my employer. I did a successful teams recording last week.
I hope we will receive a windows update soon so I can test.

**Comment by zanechua** [comment]
@michiproep 

I just tested this on Windows 11 RTM and I can share the content in Teams with no issues.

I have however observed weird behavior, I suppose it's due to how the code captures the screen.

You have to start the ScreenshareHelper app first, set the area then bring the window/application you want to share and place it on top of the translucent area.

Otherwise nothing will start sharing and it'll just stay black.

**Comment by michiproep** [comment]
Hi @zanechua ,
I'm glad that it will work with other Windows versions. So, I might just close this issue.
Regarding you second comment: This is how the tool works. You drag the window over the area you want to share, click set and start sharing. Afterwards you can move the window to some other place. It will remember the last set area.

**Comment by zanechua** [comment]
well that makes more sense now that you've explained it.

PEBKAC. 😄
